<a href="https://colab.research.google.com/github/armnkumar321-spec/pythonclasses/blob/main/day6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
dct={
    'name':['tam','nick','krish','jack'],
    'age':[20,21,19,18],
    'roll no':[1,2,3,4]
}
df=pd.DataFrame(dct)
print(df)
display(df)

    name  age  roll no
0    tam   20        1
1   nick   21        2
2  krish   19        3
3   jack   18        4

    name  age  roll no
0    tam   20        1
1   nick   21        2
2  krish   19        3
3   jack   18        4

In [ ]:
import pandas as pd

df = pd.read_csv('student_data.csv')
# df.info()
# display(df)
df.head()
# display(df.head())

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed

In [ ]:
df=pd.read_csv('student_data.csv')
# df.tail(3)
# df['internet_usage']
# df[['study_hours','internet_usage']]
# df.iloc[0:5,2]
# df2=df.loc[df['study_hours']==11]
# display(df2)
df.loc[4]

study_hours                   5
attendance                   52
sleep_hours                   8
internet_usage                6
assignments_completed         8
previous_score               40
exam_score                78.82
placement_status         Placed
Name: 4, dtype: object

In [ ]:
filtered_df = df.loc[df['assignments_completed'] == 8]
display(filtered_df.iloc[1])

study_hours                   5
attendance                   52
sleep_hours                   8
internet_usage                6
assignments_completed         8
previous_score               40
exam_score                78.82
placement_status         Placed
Name: 4, dtype: object

In [ ]:
filtered_df = df.loc[df['assignments_completed'] == 8]
display(filtered_df.iloc[1])

study_hours                   5
attendance                   52
sleep_hours                   8
internet_usage                6
assignments_completed         8
previous_score               40
exam_score                78.82
placement_status         Placed
Name: 4, dtype: object

In [ ]:
# df=pd.read_csv('student_data.csv')
df[df["assignments_completed"]>3]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [ ]:
import pandas as pd


df = pd.read_csv('student_data.csv')


df = df.rename(columns={'assignments_completed': 'assign_completed'})


df = df.drop(columns=['internet_usage'])

display(df)

,study_hours,attendance,sleep_hours,assign_completed,previous_score,exam_score,placement_status
0,7,56,8,10,62,100.00,Placed
1,4,69,5,8,56,100.00,Placed
2,11,60,7,10,45,100.00,Placed
3,8,99,9,4,55,90.17,Placed
4,5,52,8,8,40,78.82,Placed
...,...,...,...,...,...,...,...
9995,2,58,9,8,88,69.31,Not Placed
9996,7,98,6,4,87,100.00,Placed
9997,10,44,8,10,37,95.94,Placed
9998,10,75,7,8,52,88.61,Placed
9999,2,70,6,16,52,78.96,Placed

In [ ]:
import pandas as pd
dct={
    'name':['tam','nick','krish','jack'],
    'age':[20,21,19,18],
    'roll no':[1,2,3,4]
}
df=pd.DataFrame(dct)
display(df)

    name  age  roll no
0    tam   20        1
1   nick   21        2
2  krish   19        3
3   jack   18        4

In [ ]:
df_with_na = pd.DataFrame({
    'A': [1, 2, None, 4],
    'B': [5, None, 7, 8]
    })
display(df_with_na)
df_2=df_with_na.fillna(1)
display(df_2)

df_dropped_from_dct = df_with_na.dropna()
print("DataFrame after applying dropna():")
display(df_dropped_from_dct)
df=df_with_na.isnull()
display(df)
df_1=df_with_na.notnull()
display(df_1)

     A    B
0  1.0  5.0
1  2.0  NaN
2  NaN  7.0
3  4.0  8.0

     A    B
0  1.0  5.0
1  2.0  1.0
2  1.0  7.0
3  4.0  8.0

DataFrame after applying dropna():

     A    B
0  1.0  5.0
3  4.0  8.0

       A      B
0  False  False
1  False   True
2   True  False
3  False  False

       A      B
0   True   True
1   True  False
2  False   True
3   True   True

In [ ]:
df_with_na = pd.DataFrame({'A': [1, 2, None, 4], 'B': [5, None, 7, 8]})
# display(df_with_na)
df=df.fillna(1)
display(df)

    name    age  roll no
0  False  False    False
1  False  False    False
2  False  False    False
3  False  False    False

In [ ]:
df_example = pd.DataFrame({'A': [1, 2, None, 4], 'B': [None, 6, 7, 8]})
print("Original DataFrame with NaNs:")
display(df_example)

df_filled = df_example.fillna(0)
print("DataFrame after fillna(0):")
display(df_filled)

Original DataFrame with NaNs:

     A    B
0  1.0  NaN
1  2.0  6.0
2  NaN  7.0
3  4.0  8.0

DataFrame after fillna(0):

     A    B
0  1.0  0.0
1  2.0  6.0
2  0.0  7.0
3  4.0  8.0

In [ ]:
df_sample = pd.DataFrame({
    'Category': ['A', 'B', 'A', 'C', 'B', 'A'],
    'Value': [10, 20, 10, 30, 20, 40]
})
print("Original DataFrame:")
display(df_sample)

unique_categories = df_sample['Category'].unique()
print("Unique categories:")
print(unique_categories)

unique_values = df_sample['Value'].unique()
print("Unique values:")
print(unique_values)

Original DataFrame:

  Category  Value
0        A     10
1        B     20
2        A     10
3        C     30
4        B     20
5        A     40

Unique categories:
['A' 'B' 'C']
Unique values:
[10 20 30 40]