<a href="https://colab.research.google.com/github/armnkumar321-spec/pythonclasses/blob/main/day7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import pandas as pd
df=pd.read_csv('student_data.csv')
df.groupby('study_hours')['exam_score'].mean()

study_hours
1     71.264562
2     75.169142
3     78.974939
4     81.845483
5     84.964142
6     88.620043
7     90.539568
8     93.297697
9     95.462126
10    96.574628
11    97.303283
Name: exam_score, dtype: float64

In [ ]:
df.groupby('placement_status')['placement_status'].agg('count')

placement_status
Not Placed    1644
Placed        8356
Name: placement_status, dtype: int64

In [ ]:
df.groupby('placement_status')['exam_score'].agg('mean')

placement_status
Not Placed    59.804653
Placed        91.996556
Name: exam_score, dtype: float64

In [ ]:
df.groupby('placement_status')['study_hours'].agg('mean')

placement_status
Not Placed    3.130170
Placed        6.552178
Name: study_hours, dtype: float64

In [ ]:
import pandas as pd
df=pd.read_csv('student_data.csv')
df.groupby('study_hours')['exam_score'].mean()

study_hours
1     71.264562
2     75.169142
3     78.974939
4     81.845483
5     84.964142
6     88.620043
7     90.539568
8     93.297697
9     95.462126
10    96.574628
11    97.303283
Name: exam_score, dtype: float64

In [ ]:
def get_grade(marks):
    if marks >= 90:
        return "A"
    elif marks >= 80:
        return "B"
    elif marks >= 70:
        return "C"
    elif marks >= 60:
        return "D"
    else:
        return "F"
df['grade']=df['exam_score'].apply(get_grade)

NameError: name 'df' is not defined