<a href="https://colab.research.google.com/github/armnkumar321-spec/pythonclasses/blob/main/Day8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df1 = pd.DataFrame({
	'id':[1,2,3,4],
	'name':['aman','kumar','raj','aj'],
	'age':[12,15,11,10]

	})
df2=pd.DataFrame({
	'id':[3,4,5,6],
	'name':['adi','d','m','q'],
	'age':[10,11,12,13]
	})
df3=pd.merge(df1,df2,on='id',how='inner')
print("/n")
print(df3)

/n
   id name_x  age_x name_y  age_y
0   3    raj     11    adi     10
1   4     aj     10      d     11

In [ ]:
import pandas as pd

df1 = pd.DataFrame({
	'id':[1,2,3,4],
	'name':['aman','kumar','raj','aj'],
	'age':[12,15,11,10]

	})
df2=pd.DataFrame({
	'id':[3,4,5,6],
	'name':['adi','d','m','q'],
	'age':[10,11,12,13]
	})
df4=pd.merge(df1,df2,on='id',how='left')
print(df4)

   id name_x  age_x name_y  age_y
0   1   aman     12    NaN    NaN
1   2  kumar     15    NaN    NaN
2   3    raj     11    adi   10.0
3   4     aj     10      d   11.0

In [ ]:
df1 = pd.DataFrame({
	'id':[1,2,3,4],
	'name':['aman','kumar','raj','aj'],
	'age':[12,15,11,10]

	})
df2=pd.DataFrame({
	'id':[3,4,5,6],
	'name':['adi','d','m','q'],
	'age':[10,11,12,13]
	})
df5=pd.merge(df1,df2,on='id',how='right')
print(df5)

   id name_x  age_x name_y  age_y
0   3    raj   11.0    adi     10
1   4     aj   10.0      d     11
2   5    NaN    NaN      m     12
3   6    NaN    NaN      q     13

In [ ]:
f1 = pd.DataFrame({
	'id':[1,2,3,4],
	'name':['aman','kumar','raj','aj'],
	'age':[12,15,11,10]

	})
df2=pd.DataFrame({
	'id':[3,4,5,6],
	'name':['adi','d','m','q'],
	'age':[10,11,12,13]
	})
df6=pd.merge(df1,df2,on='id',how='right')
print(df6)

   id name_x  age_x name_y  age_y
0   3    raj   11.0    adi     10
1   4     aj   10.0      d     11
2   5    NaN    NaN      m     12
3   6    NaN    NaN      q     13

In [ ]:
f1 = pd.DataFrame({
	'id':[1,2,3,4],
	'name':['aman','kumar','raj','aj'],
	'age':[12,15,11,10]

	})
df2=pd.DataFrame({
	'id':[3,4,5,6],
	'name':['adi','d','m','q'],
	'age':[10,11,12,13]
	})
df7=pd.merge(df1,df2,how='cross')
print(df7)

    id_x name_x  age_x  id_y name_y  age_y
0      1   aman     12     3    adi     10
1      1   aman     12     4      d     11
2      1   aman     12     5      m     12
3      1   aman     12     6      q     13
4      2  kumar     15     3    adi     10
5      2  kumar     15     4      d     11
6      2  kumar     15     5      m     12
7      2  kumar     15     6      q     13
8      3    raj     11     3    adi     10
9      3    raj     11     4      d     11
10     3    raj     11     5      m     12
11     3    raj     11     6      q     13
12     4     aj     10     3    adi     10
13     4     aj     10     4      d     11
14     4     aj     10     5      m     12
15     4     aj     10     6      q     13

In [ ]:
df1 = pd.DataFrame({
	'id':[1,2,3,4],
	'name':['aman','kumar','raj','aj'],
	'age':[12,15,11,10]

	})
df2=pd.DataFrame({
	'id':[3,4,5,6],
	'name':['adi','d','m','q'],
	'age':[10,11,12,13]
	})
df8=pd.concat([df1,df2])
print(df8)

   id   name  age
0   1   aman   12
1   2  kumar   15
2   3    raj   11
3   4     aj   10
0   3    adi   10
1   4      d   11
2   5      m   12
3   6      q   13

In [ ]:
df1 = pd.DataFrame({
	'id':[1,2,3,4],
	'name':['aman','kumar','raj','aj'],
	'age':[12,15,11,10]

	})
df2=pd.DataFrame({
	'id':[3,4,5,6],
	'name':['adi','d','m','q'],
	'age':[10,11,12,13]
	})
df8=pd.concat([df1,df2], ignore_index=True)
df9=df8.drop_duplicates(subset=['id','name'],keep='first')
print(df9)

   id   name  age
0   1   aman   12
1   2  kumar   15
2   3    raj   11
3   4     aj   10
0   3    adi   10
1   4      d   11
2   5      m   12
3   6      q   13

In [ ]:
import pandas as pd
student_df = pd.read_csv('/content/student_data.csv')
student_df.pivot_table(columns='placement_status',index='sleep_hours',values='exam_score',aggfunc='mean')

placement_status  Not Placed     Placed
sleep_hours
4                  59.424160  90.483113
5                  58.306079  91.085519
6                  60.971968  91.819595
7                  59.650121  92.279986
8                  60.091122  93.062072
9                  61.181129  92.987227

In [ ]:
import pandas as pd
student_df = pd.read_csv('/content/student_data.csv')
student_df.pivot_table(columns='study_hours',index='sleep_hours',values='exam_score',aggfunc='mean')

study_hours,1,2,3,4,5,6,7,8,9,10,11
sleep_hours,,,,,,,,,,,
4,66.129216,70.614122,75.031522,76.034040,80.735396,85.456599,86.620056,92.007708,93.117643,94.575482,95.856752
5,67.332622,71.107432,77.084935,80.251067,82.293846,86.513837,89.612197,90.594815,94.710988,95.901617,96.798027
6,71.643253,75.443014,78.361465,80.603052,84.592267,88.487006,90.060073,93.206014,94.143655,96.234167,97.256269
7,72.272215,74.967901,79.763585,83.286929,84.861746,89.331875,92.353125,93.360491,96.438431,97.519940,96.993237
8,74.310414,78.154903,80.104462,86.069697,88.321386,90.860464,92.392548,94.406839,97.455686,97.801867,98.446467
9,76.144403,80.536467,83.070186,85.211288,88.425503,91.437872,92.384785,95.841733,96.849357,97.514568,98.574894

homework->1327
511
586
1050
175
181
182
262
184
185
1179

In [ ]:
print(6/2)

3.0